SHOW GRANTS TO ROLE movies_dlt_role;

USE ROLE USERADMIN;
GRANT ROLE movies_dlt_role TO USER kristoferfangrat;

USE ROLE movies_dlt_role;

SHOW DATABASES;

USE DATABASE MOVIES;
SHOW SCHEMAS;

USE SCHEMA STAGING;

SHOW TABLES;
SELECT * FROM NETFLIX;
