Table fct_reviews {
  fct_reviews_id INTERGER [primary key]
  rating INTEGER [NOT NULL]
  stars INTEGER [NOT NULL]
  authors_id INTEGER [ref: > dim_authors.authors_id]
  products_id INTEGER [ref: > dim_products.products_id]
  review_id INTEGER [ref: > dim_review.review_id]

}

Table dim_authors {
  authors_id INTEGER [primary key]
  name VARCHAR(30) [NOT NULL]
}

Table dim_products {
  products_id INTEGER [primary key]
  product_name VARCHAR(50) [NOT NULL]
  ingredients VARCHAR(200) [NOT NULL]
  description VARCHAR(150) [NOT NULL]

}

Table dim_review {
review_id INTEGER [primary key]
title VARCHAR(100) [NOT NULL]
text VARCHAR(200) [NOT NULL]
date DATETIME [NOT NULL]
}