SELECT
    PROPERTIES__CITY_DISTRICT AS DISTRICT,
    PROPERTIES__STREET_NAME AS STREET,
    PROPERTIES__PARKING_RATE AS RATE
FROM 
    parking_data
WHERE
    PROPERTIES__CITY_DISTRICT IN ('Östermalm', 'Kungsholmen', 'Södermalm')
LIMIT 10;
SELECT
    PROPERTIES__CITY_DISTRICT AS DISTRICT,
    PROPERTIES__STREET_NAME AS STREET,
    PROPERTIES__PARKING_RATE AS RATE
FROM 
    parking_data_mc
WHERE
    PROPERTIES__CITY_DISTRICT IN ('Östermalm', 'Kungsholmen', 'Södermalm')
LIMIT 10;


SELECT COUNT(*) FROM parking_data_mc;

SELECT * FROM parking_data_mc LIMIT 10;