USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS parking;

CREATE SCHEMA IF NOT EXISTS parking.staging;

CREATE WAREHOUSE parking_wh
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
COMMENT = 'Warehouse for parking data';